<?php
/**
* Class to handle requests to LeverateCrm webservice.
* This code was generated by using SoapProxy tool by przemek@otn.pl
* Please do not modify it by hand.
*
*/
class LeverateCrm extends SoapProxy {
	protected $defaultTypeMap = array(
		"char" => "char",
		"duration" => "duration",
		"guid" => "guid",
		"ArrayOfstring" => "ArrayOfstring",
		"DayOfWeek" => "DayOfWeek",
		"LoginResponse" => "LoginResponse",
		"ResultInfo" => "ResultInfo",
		"ResultCode" => "ResultCode",
		"AccountDetailsRequest" => "AccountDetailsRequest",
		"AccountDetailsRequestFilterType" => "AccountDetailsRequestFilterType",
		"AccountInfoResponse" => "AccountInfoResponse",
		"ArrayOfAccountInfo" => "ArrayOfAccountInfo",
		"AccountInfo" => "AccountInfo",
		"PickListInfo" => "PickListInfo",
		"ArrayOfDynamicAttributeInfo" => "ArrayOfDynamicAttributeInfo",
		"DynamicAttributeInfo" => "DynamicAttributeInfo",
		"DynamicAttributeType" => "DynamicAttributeType",
		"EnvironmentInfo" => "EnvironmentInfo",
		"MarketingInfo" => "MarketingInfo",
		"ArrayOfTradingPlatformAccountInfo" => "ArrayOfTradingPlatformAccountInfo",
		"TradingPlatformAccountInfo" => "TradingPlatformAccountInfo",
		"CurrencyInfo" => "CurrencyInfo",
		"TradingPlatformInfo" => "TradingPlatformInfo",
		"TradingPlatformType" => "TradingPlatformType",
		"TradingPlatformAccountInfoResponse" => "TradingPlatformAccountInfoResponse",
		"TradingPlatformAccountBalanceResponse" => "TradingPlatformAccountBalanceResponse",
		"TradingPlatformAccountBalance" => "TradingPlatformAccountBalance",
		"UpdateAccountDetailsRequest" => "UpdateAccountDetailsRequest",
		"RealAccountRegistrationRequest" => "RealAccountRegistrationRequest",
		"AccountRegistrationRequest" => "AccountRegistrationRequest",
		"AccountRegistrationResponse" => "AccountRegistrationResponse",
		"TradingPlatformAccountType" => "TradingPlatformAccountType",
		"DuplicationHandlingResult" => "DuplicationHandlingResult",
		"LeadAccountRegistrationRequest" => "LeadAccountRegistrationRequest",
		"DemoAccountRegistrationRequest" => "DemoAccountRegistrationRequest",
		"CaseCreationRequest" => "CaseCreationRequest",
		"WithdrawalRequest" => "WithdrawalRequest",
		"CreditCardInfo" => "CreditCardInfo",
		"WebMoneyInfo" => "WebMoneyInfo",
		"WireTransferInfo" => "WireTransferInfo",
		"MoneyTransactionMethod" => "MoneyTransactionMethod",
		"CreditCardDepositResponse" => "CreditCardDepositResponse",
		"MonetaryTransactionRequest" => "MonetaryTransactionRequest",
		"MonetaryTransactionRequestInfo" => "MonetaryTransactionRequestInfo",
		"PaymentInfo" => "PaymentInfo",
		"KashUPaymentInfo" => "KashUPaymentInfo",
		"CashPaymentInfo" => "CashPaymentInfo",
		"ChequePaymentInfo" => "ChequePaymentInfo",
		"CreditCardPaymentInfo" => "CreditCardPaymentInfo",
		"MoneyBookersPaymentInfo" => "MoneyBookersPaymentInfo",
		"EWalletPaymentInfo" => "EWalletPaymentInfo",
		"WebMoneyRequestInfo" => "WebMoneyRequestInfo",
		"NetellerPaymentInfo" => "NetellerPaymentInfo",
		"PaypalPaymentInfo" => "PaypalPaymentInfo",
		"WesternUnionPaymentInfo" => "WesternUnionPaymentInfo",
		"WireTransferPaymentInfo" => "WireTransferPaymentInfo",
		"InternalPaymentInfo" => "InternalPaymentInfo",
		"WithdrawalMonetaryTransactionRequest" => "WithdrawalMonetaryTransactionRequest",
		"DepositRequest" => "DepositRequest",
		"BonusRequest" => "BonusRequest",
		"TransferBetweenTPAccountsRequest" => "TransferBetweenTPAccountsRequest",
		"MonetaryTransactionResponse" => "MonetaryTransactionResponse",
		"TradingHistoryResponse" => "TradingHistoryResponse",
		"ArrayOfClosedPositionInfo" => "ArrayOfClosedPositionInfo",
		"ClosedPositionInfo" => "ClosedPositionInfo",
		"ActionType" => "ActionType",
		"AccountMonetaryStatementResponse" => "AccountMonetaryStatementResponse",
		"ArrayOfMonetaryTransaction" => "ArrayOfMonetaryTransaction",
		"MonetaryTransaction" => "MonetaryTransaction",
		"MonetaryTransactionInternalType" => "MonetaryTransactionInternalType",
		"MonetaryTransactionType" => "MonetaryTransactionType",
		"ArrayOfPickListInfo" => "ArrayOfPickListInfo",
		"ArrayOfCountryInfo" => "ArrayOfCountryInfo",
		"CountryInfo" => "CountryInfo",
		"ArrayOfCurrencyInfo" => "ArrayOfCurrencyInfo",
		"CreditCardDepositRequest" => "CreditCardDepositRequest",
		"LoginAccount" => "LoginAccount",
		"LoginAccountResponse" => "LoginAccountResponse",
		"ChangePassword" => "ChangePassword",
		"ChangePasswordResponse" => "ChangePasswordResponse",
		"GetAccountDetails" => "GetAccountDetails",
		"GetAccountDetailsResponse" => "GetAccountDetailsResponse",
		"GetTradingPlatformAccountDetails" => "GetTradingPlatformAccountDetails",
		"GetTradingPlatformAccountDetailsResponse" => "GetTradingPlatformAccountDetailsResponse",
		"GetTradingPlatformAccountBalance" => "GetTradingPlatformAccountBalance",
		"GetTradingPlatformAccountBalanceResponse" => "GetTradingPlatformAccountBalanceResponse",
		"UpdateAccountDetails" => "UpdateAccountDetails",
		"UpdateAccountDetailsResponse" => "UpdateAccountDetailsResponse",
		"RegisterRealAccount" => "RegisterRealAccount",
		"RegisterRealAccountResponse" => "RegisterRealAccountResponse",
		"RegisterLeadAccount" => "RegisterLeadAccount",
		"RegisterLeadAccountResponse" => "RegisterLeadAccountResponse",
		"RegisterDemoAccount" => "RegisterDemoAccount",
		"RegisterDemoAccountResponse" => "RegisterDemoAccountResponse",
		"CreateCase" => "CreateCase",
		"CreateCaseResponse" => "CreateCaseResponse",
		"CreateWithdrawalRequest" => "CreateWithdrawalRequest",
		"CreateWithdrawalRequestResponse" => "CreateWithdrawalRequestResponse",
		"CreateCreditCardDepositRequest" => "CreateCreditCardDepositRequest",
		"CreateCreditCardDepositRequestResponse" => "CreateCreditCardDepositRequestResponse",
		"CreateMonetaryTransaction" => "CreateMonetaryTransaction",
		"CreateMonetaryTransactionResponse" => "CreateMonetaryTransactionResponse",
		"GetTradingHistory" => "GetTradingHistory",
		"GetTradingHistoryResponse" => "GetTradingHistoryResponse",
		"GetAccountMonetaryStatement" => "GetAccountMonetaryStatement",
		"GetAccountMonetaryStatementResponse" => "GetAccountMonetaryStatementResponse",
		"ForgotYourPassword" => "ForgotYourPassword",
		"ForgotYourPasswordResponse" => "ForgotYourPasswordResponse",
		"UploadFile" => "UploadFile",
		"UploadFileResponse" => "UploadFileResponse",
		"GetPickListInfoItems" => "GetPickListInfoItems",
		"GetPickListInfoItemsResponse" => "GetPickListInfoItemsResponse",
		"GetCountries" => "GetCountries",
		"GetCountriesResponse" => "GetCountriesResponse",
		"GetCurrencies" => "GetCurrencies",
		"GetCurrenciesResponse" => "GetCurrenciesResponse",
		"GetTradingPlatformGroups" => "GetTradingPlatformGroups",
		"GetTradingPlatformGroupsResponse" => "GetTradingPlatformGroupsResponse",
		"ExceptionDetail" => "ExceptionDetail"
	);

	/**
	* Genarated webservice method LoginAccount
	*
	* @param LoginAccount $parameters
	* @return LoginAccountResponse
	*/
	public function LoginAccount(LoginAccount $parameters) {
		return $this->soapClient->LoginAccount($parameters);
	}

	/**
	* Genarated webservice method ChangePassword
	*
	* @param ChangePassword $parameters
	* @return ChangePasswordResponse
	*/
	public function ChangePassword(ChangePassword $parameters) {
		return $this->soapClient->ChangePassword($parameters);
	}

	/**
	* Genarated webservice method GetAccountDetails
	*
	* @param GetAccountDetails $parameters
	* @return GetAccountDetailsResponse
	*/
	public function GetAccountDetails(GetAccountDetails $parameters) {
		return $this->soapClient->GetAccountDetails($parameters);
	}

	/**
	* Genarated webservice method GetTradingPlatformAccountDetails
	*
	* @param GetTradingPlatformAccountDetails $parameters
	* @return GetTradingPlatformAccountDetailsResponse
	*/
	public function GetTradingPlatformAccountDetails(GetTradingPlatformAccountDetails $parameters) {
		return $this->soapClient->GetTradingPlatformAccountDetails($parameters);
	}

	/**
	* Genarated webservice method GetTradingPlatformAccountBalance
	*
	* @param GetTradingPlatformAccountBalance $parameters
	* @return GetTradingPlatformAccountBalanceResponse
	*/
	public function GetTradingPlatformAccountBalance(GetTradingPlatformAccountBalance $parameters) {
		return $this->soapClient->GetTradingPlatformAccountBalance($parameters);
	}

	/**
	* Genarated webservice method UpdateAccountDetails
	*
	* @param UpdateAccountDetails $parameters
	* @return UpdateAccountDetailsResponse
	*/
	public function UpdateAccountDetails(UpdateAccountDetails $parameters) {
		return $this->soapClient->UpdateAccountDetails($parameters);
	}

	/**
	* Genarated webservice method RegisterRealAccount
	*
	* @param RegisterRealAccount $parameters
	* @return RegisterRealAccountResponse
	*/
	public function RegisterRealAccount(RegisterRealAccount $parameters) {
		return $this->soapClient->RegisterRealAccount($parameters);
	}

	/**
	* Genarated webservice method RegisterLeadAccount
	*
	* @param RegisterLeadAccount $parameters
	* @return RegisterLeadAccountResponse
	*/
	public function RegisterLeadAccount(RegisterLeadAccount $parameters) {
		return $this->soapClient->RegisterLeadAccount($parameters);
	}

	/**
	* Genarated webservice method RegisterDemoAccount
	*
	* @param RegisterDemoAccount $parameters
	* @return RegisterDemoAccountResponse
	*/
	public function RegisterDemoAccount(RegisterDemoAccount $parameters) {
		return $this->soapClient->RegisterDemoAccount($parameters);
	}

	/**
	* Genarated webservice method CreateCase
	*
	* @param CreateCase $parameters
	* @return CreateCaseResponse
	*/
	public function CreateCase(CreateCase $parameters) {
		return $this->soapClient->CreateCase($parameters);
	}

	/**
	* Genarated webservice method CreateWithdrawalRequest
	*
	* @param CreateWithdrawalRequest $parameters
	* @return CreateWithdrawalRequestResponse
	*/
	public function CreateWithdrawalRequest(CreateWithdrawalRequest $parameters) {
		return $this->soapClient->CreateWithdrawalRequest($parameters);
	}

	/**
	* Genarated webservice method CreateCreditCardDepositRequest
	*
	* @param CreateCreditCardDepositRequest $parameters
	* @return CreateCreditCardDepositRequestResponse
	*/
	public function CreateCreditCardDepositRequest(CreateCreditCardDepositRequest $parameters) {
		return $this->soapClient->CreateCreditCardDepositRequest($parameters);
	}

	/**
	* Genarated webservice method CreateMonetaryTransaction
	*
	* @param CreateMonetaryTransaction $parameters
	* @return CreateMonetaryTransactionResponse
	*/
	public function CreateMonetaryTransaction(CreateMonetaryTransaction $parameters) {
		return $this->soapClient->CreateMonetaryTransaction($parameters);
	}

	/**
	* Genarated webservice method GetTradingHistory
	*
	* @param GetTradingHistory $parameters
	* @return GetTradingHistoryResponse
	*/
	public function GetTradingHistory(GetTradingHistory $parameters) {
		return $this->soapClient->GetTradingHistory($parameters);
	}

	/**
	* Genarated webservice method GetAccountMonetaryStatement
	*
	* @param GetAccountMonetaryStatement $parameters
	* @return GetAccountMonetaryStatementResponse
	*/
	public function GetAccountMonetaryStatement(GetAccountMonetaryStatement $parameters) {
		return $this->soapClient->GetAccountMonetaryStatement($parameters);
	}

	/**
	* Genarated webservice method ForgotYourPassword
	*
	* @param ForgotYourPassword $parameters
	* @return ForgotYourPasswordResponse
	*/
	public function ForgotYourPassword(ForgotYourPassword $parameters) {
		return $this->soapClient->ForgotYourPassword($parameters);
	}

	/**
	* Genarated webservice method UploadFile
	*
	* @param UploadFile $parameters
	* @return UploadFileResponse
	*/
	public function UploadFile(UploadFile $parameters) {
		return $this->soapClient->UploadFile($parameters);
	}

	/**
	* Genarated webservice method GetPickListInfoItems
	*
	* @param GetPickListInfoItems $parameters
	* @return GetPickListInfoItemsResponse
	*/
	public function GetPickListInfoItems(GetPickListInfoItems $parameters) {
		return $this->soapClient->GetPickListInfoItems($parameters);
	}

	/**
	* Genarated webservice method GetCountries
	*
	* @param GetCountries $parameters
	* @return GetCountriesResponse
	*/
	public function GetCountries(GetCountries $parameters) {
		return $this->soapClient->GetCountries($parameters);
	}

	/**
	* Genarated webservice method GetCurrencies
	*
	* @param GetCurrencies $parameters
	* @return GetCurrenciesResponse
	*/
	public function GetCurrencies(GetCurrencies $parameters) {
		return $this->soapClient->GetCurrencies($parameters);
	}

	/**
	* Genarated webservice method GetTradingPlatformGroups
	*
	* @param GetTradingPlatformGroups $parameters
	* @return GetTradingPlatformGroupsResponse
	*/
	public function GetTradingPlatformGroups(GetTradingPlatformGroups $parameters) {
		return $this->soapClient->GetTradingPlatformGroups($parameters);
	}



} //end generated proxy class


/**********SOAP TYPES***********/

/**
* Generated data proxy class for int char
*
*/
class char {

}

/**
* Generated data proxy class for duration duration
*
*/
class duration {

}

/**
* Generated data proxy class for string guid
*
*/
class guid {

}

/**
* Generated data proxy class for struct ArrayOfstring
*
*/
class ArrayOfstring {

	/**
	* @var string $string
	*/
	public $string;

}

/**
* Generated data proxy class for string DayOfWeek
*
*/
class DayOfWeek {

}

/**
* Generated data proxy class for struct LoginResponse
*
*/
class LoginResponse {

	/**
	* @var guid $AccountId
	*/
	public $AccountId;

	/**
	* @var string $ContentType
	*/
	public $ContentType;

	/**
	* @var dateTime $LastLoginTime
	*/
	public $LastLoginTime;

	/**
	* @var ResultInfo $Result
	*/
	public $Result;

	/**
	* @var guid $TradingPlatformAccountId
	*/
	public $TradingPlatformAccountId;

}

/**
* Generated data proxy class for struct ResultInfo
*
*/
class ResultInfo {

	/**
	* @var ResultCode $Code
	*/
	public $Code;

	/**
	* @var string $Message
	*/
	public $Message;

	/**
	* @var guid $RequestId
	*/
	public $RequestId;

}

/**
* Generated data proxy class for string ResultCode
*
*/
class ResultCode {

}

/**
* Generated data proxy class for struct AccountDetailsRequest
*
*/
class AccountDetailsRequest {

	/**
	* @var ArrayOfstring $AdditionalAttributesNames
	*/
	public $AdditionalAttributesNames;

	/**
	* @var AccountDetailsRequestFilterType $FilterType
	*/
	public $FilterType;

	/**
	* @var string $FilterValue
	*/
	public $FilterValue;

}

/**
* Generated data proxy class for string AccountDetailsRequestFilterType
*
*/
class AccountDetailsRequestFilterType {

}

/**
* Generated data proxy class for struct AccountInfoResponse
*
*/
class AccountInfoResponse {

	/**
	* @var ArrayOfAccountInfo $AccountsInfo
	*/
	public $AccountsInfo;

	/**
	* @var ResultInfo $Result
	*/
	public $Result;

}

/**
* Generated data proxy class for struct ArrayOfAccountInfo
*
*/
class ArrayOfAccountInfo {

	/**
	* @var AccountInfo $AccountInfo
	*/
	public $AccountInfo;

}

/**
* Generated data proxy class for struct AccountInfo
*
*/
class AccountInfo {

	/**
	* @var boolean $AcceptTermsAndConditions
	*/
	public $AcceptTermsAndConditions;

	/**
	* @var PickListInfo $AccountType
	*/
	public $AccountType;

	/**
	* @var ArrayOfDynamicAttributeInfo $AdditionalAttributes
	*/
	public $AdditionalAttributes;

	/**
	* @var string $AdditionalInfo1
	*/
	public $AdditionalInfo1;

	/**
	* @var string $AdditionalInfo2
	*/
	public $AdditionalInfo2;

	/**
	* @var string $AdditionalInfo3
	*/
	public $AdditionalInfo3;

	/**
	* @var string $Address1
	*/
	public $Address1;

	/**
	* @var string $Address2
	*/
	public $Address2;

	/**
	* @var boolean $ApiTrading
	*/
	public $ApiTrading;

	/**
	* @var boolean $ApproveReceiveCommercial
	*/
	public $ApproveReceiveCommercial;

	/**
	* @var PickListInfo $AverageTradeSize
	*/
	public $AverageTradeSize;

	/**
	* @var PickListInfo $CfdTradingExperience
	*/
	public $CfdTradingExperience;

	/**
	* @var string $City
	*/
	public $City;

	/**
	* @var string $ContentType
	*/
	public $ContentType;

	/**
	* @var string $Country
	*/
	public $Country;

	/**
	* @var string $CountryOfCitizenship
	*/
	public $CountryOfCitizenship;

	/**
	* @var PickListInfo $CurrenciesTradingExperience
	*/
	public $CurrenciesTradingExperience;

	/**
	* @var dateTime $DateOfBirth
	*/
	public $DateOfBirth;

	/**
	* @var boolean $DisabledTradingPlatformAccountExists
	*/
	public $DisabledTradingPlatformAccountExists;

	/**
	* @var string $Email
	*/
	public $Email;

	/**
	* @var EnvironmentInfo $EnvironmentInfo
	*/
	public $EnvironmentInfo;

	/**
	* @var int $EstimatedAnnualIncome
	*/
	public $EstimatedAnnualIncome;

	/**
	* @var int $EstimatedNetWorth
	*/
	public $EstimatedNetWorth;

	/**
	* @var string $FirstName
	*/
	public $FirstName;

	/**
	* @var PickListInfo $FuturesTradingExperience
	*/
	public $FuturesTradingExperience;

	/**
	* @var boolean $HasDemoExperience
	*/
	public $HasDemoExperience;

	/**
	* @var PickListInfo $HowDidYouHearAboutUs
	*/
	public $HowDidYouHearAboutUs;

	/**
	* @var guid $Id
	*/
	public $Id;

	/**
	* @var string $LastName
	*/
	public $LastName;

	/**
	* @var boolean $ManagedAccount
	*/
	public $ManagedAccount;

	/**
	* @var MarketingInfo $MarketingInfo
	*/
	public $MarketingInfo;

	/**
	* @var string $MobileNumber
	*/
	public $MobileNumber;

	/**
	* @var PickListInfo $NumberOfTimesTradedInPastYear
	*/
	public $NumberOfTimesTradedInPastYear;

	/**
	* @var string $Occupation
	*/
	public $Occupation;

	/**
	* @var PickListInfo $OptionsTradingExperience
	*/
	public $OptionsTradingExperience;

	/**
	* @var string $OwningBusinessUnit
	*/
	public $OwningBusinessUnit;

	/**
	* @var string $Phone1AreaCode
	*/
	public $Phone1AreaCode;

	/**
	* @var string $Phone1CountryCode
	*/
	public $Phone1CountryCode;

	/**
	* @var string $Phone1Number
	*/
	public $Phone1Number;

	/**
	* @var string $PhoneAreaCode
	*/
	public $PhoneAreaCode;

	/**
	* @var string $PhoneCountryCode
	*/
	public $PhoneCountryCode;

	/**
	* @var string $PhoneNumber
	*/
	public $PhoneNumber;

	/**
	* @var string $PlaceOfBirth
	*/
	public $PlaceOfBirth;

	/**
	* @var PickListInfo $SecuritiesTradingExperience
	*/
	public $SecuritiesTradingExperience;

	/**
	* @var boolean $SendSMS
	*/
	public $SendSMS;

	/**
	* @var string $SocialSecurityNumber
	*/
	public $SocialSecurityNumber;

	/**
	* @var string $State
	*/
	public $State;

	/**
	* @var boolean $SuppliedNecessaryDocuments
	*/
	public $SuppliedNecessaryDocuments;

	/**
	* @var PickListInfo $Title
	*/
	public $Title;

	/**
	* @var ArrayOfTradingPlatformAccountInfo $TradingPlatformAccounts
	*/
	public $TradingPlatformAccounts;

	/**
	* @var string $ZipCode
	*/
	public $ZipCode;

}

/**
* Generated data proxy class for struct PickListInfo
*
*/
class PickListInfo {

	/**
	* @var string $Name
	*/
	public $Name;

	/**
	* @var int $Value
	*/
	public $Value;

}

/**
* Generated data proxy class for struct ArrayOfDynamicAttributeInfo
*
*/
class ArrayOfDynamicAttributeInfo {

	/**
	* @var DynamicAttributeInfo $DynamicAttributeInfo
	*/
	public $DynamicAttributeInfo;

}

/**
* Generated data proxy class for struct DynamicAttributeInfo
*
*/
class DynamicAttributeInfo {

	/**
	* @var DynamicAttributeType $DynamicAttributeType
	*/
	public $DynamicAttributeType;

	/**
	* @var string $Name
	*/
	public $Name;

	/**
	* @var boolean $ShouldOverride
	*/
	public $ShouldOverride;

	/**
	* @var anyType $Value
	*/
	public $Value;

}

/**
* Generated data proxy class for string DynamicAttributeType
*
*/
class DynamicAttributeType {

}

/**
* Generated data proxy class for struct EnvironmentInfo
*
*/
class EnvironmentInfo {

	/**
	* @var string $Browser
	*/
	public $Browser;

	/**
	* @var string $IpAddress
	*/
	public $IpAddress;

	/**
	* @var guid $IpCountryId
	*/
	public $IpCountryId;

	/**
	* @var string $Language
	*/
	public $Language;

	/**
	* @var string $OperationSystem
	*/
	public $OperationSystem;

	/**
	* @var string $Resolution
	*/
	public $Resolution;

}

/**
* Generated data proxy class for struct MarketingInfo
*
*/
class MarketingInfo {

	/**
	* @var string $ADData
	*/
	public $ADData;

	/**
	* @var string $AdsServer
	*/
	public $AdsServer;

	/**
	* @var string $Affiliate
	*/
	public $Affiliate;

	/**
	* @var string $AffiliateTransactionId
	*/
	public $AffiliateTransactionId;

	/**
	* @var string $CampaignId
	*/
	public $CampaignId;

	/**
	* @var string $GoogleId
	*/
	public $GoogleId;

	/**
	* @var string $IntroducingBrokerEmail
	*/
	public $IntroducingBrokerEmail;

	/**
	* @var string $LinkId
	*/
	public $LinkId;

	/**
	* @var string $Referrer
	*/
	public $Referrer;

	/**
	* @var string $SubAffiliate
	*/
	public $SubAffiliate;

	/**
	* @var string $TLID
	*/
	public $TLID;

	/**
	* @var string $Tag
	*/
	public $Tag;

	/**
	* @var string $Tag1
	*/
	public $Tag1;

	/**
	* @var string $UtmCampaign
	*/
	public $UtmCampaign;

	/**
	* @var string $UtmContent
	*/
	public $UtmContent;

	/**
	* @var string $UtmCreative
	*/
	public $UtmCreative;

	/**
	* @var string $UtmMedium
	*/
	public $UtmMedium;

	/**
	* @var string $UtmSource
	*/
	public $UtmSource;

	/**
	* @var string $UtmTerm
	*/
	public $UtmTerm;

	/**
	* @var string $WhiteLabel
	*/
	public $WhiteLabel;

}

/**
* Generated data proxy class for struct ArrayOfTradingPlatformAccountInfo
*
*/
class ArrayOfTradingPlatformAccountInfo {

	/**
	* @var TradingPlatformAccountInfo $TradingPlatformAccountInfo
	*/
	public $TradingPlatformAccountInfo;

}

/**
* Generated data proxy class for struct TradingPlatformAccountInfo
*
*/
class TradingPlatformAccountInfo {

	/**
	* @var boolean $AccountDisabledOnTradingPlatform
	*/
	public $AccountDisabledOnTradingPlatform;

	/**
	* @var boolean $AccountDoesntExistOnTradingPlatform
	*/
	public $AccountDoesntExistOnTradingPlatform;

	/**
	* @var CurrencyInfo $BaseCurrency
	*/
	public $BaseCurrency;

	/**
	* @var dateTime $CreationDate
	*/
	public $CreationDate;

	/**
	* @var dateTime $ExpirationDate
	*/
	public $ExpirationDate;

	/**
	* @var guid $Id
	*/
	public $Id;

	/**
	* @var dateTime $LastLoginTime
	*/
	public $LastLoginTime;

	/**
	* @var string $Name
	*/
	public $Name;

	/**
	* @var guid $ParentAccountId
	*/
	public $ParentAccountId;

	/**
	* @var string $Password
	*/
	public $Password;

	/**
	* @var TradingPlatformInfo $TradingPlatform
	*/
	public $TradingPlatform;

}

/**
* Generated data proxy class for struct CurrencyInfo
*
*/
class CurrencyInfo {

	/**
	* @var string $Code
	*/
	public $Code;

	/**
	* @var guid $Id
	*/
	public $Id;

	/**
	* @var string $Name
	*/
	public $Name;

	/**
	* @var string $Symbol
	*/
	public $Symbol;

}

/**
* Generated data proxy class for struct TradingPlatformInfo
*
*/
class TradingPlatformInfo {

	/**
	* @var guid $Id
	*/
	public $Id;

	/**
	* @var int $Leverage
	*/
	public $Leverage;

	/**
	* @var string $Name
	*/
	public $Name;

	/**
	* @var TradingPlatformType $Type
	*/
	public $Type;

}

/**
* Generated data proxy class for string TradingPlatformType
*
*/
class TradingPlatformType {

}

/**
* Generated data proxy class for struct TradingPlatformAccountInfoResponse
*
*/
class TradingPlatformAccountInfoResponse {

	/**
	* @var ResultInfo $Result
	*/
	public $Result;

	/**
	* @var TradingPlatformAccountInfo $TradingPlatformAccountInfo
	*/
	public $TradingPlatformAccountInfo;

}

/**
* Generated data proxy class for struct TradingPlatformAccountBalanceResponse
*
*/
class TradingPlatformAccountBalanceResponse {

	/**
	* @var ResultInfo $Result
	*/
	public $Result;

	/**
	* @var TradingPlatformAccountBalance $TradingPlatformAccountBalance
	*/
	public $TradingPlatformAccountBalance;

	/**
	* @var guid $TradingPlatformAccountId
	*/
	public $TradingPlatformAccountId;

}

/**
* Generated data proxy class for struct TradingPlatformAccountBalance
*
*/
class TradingPlatformAccountBalance {

	/**
	* @var double $Balance
	*/
	public $Balance;

	/**
	* @var double $Credit
	*/
	public $Credit;

	/**
	* @var double $Equity
	*/
	public $Equity;

	/**
	* @var double $Margin
	*/
	public $Margin;

}

/**
* Generated data proxy class for struct UpdateAccountDetailsRequest
*
*/
class UpdateAccountDetailsRequest {

	/**
	* @var guid $AccountId
	*/
	public $AccountId;

	/**
	* @var ArrayOfDynamicAttributeInfo $AdditionalAttributes
	*/
	public $AdditionalAttributes;

	/**
	* @var string $Address1
	*/
	public $Address1;

	/**
	* @var string $Address2
	*/
	public $Address2;

	/**
	* @var boolean $ApproveReceiveCommercial
	*/
	public $ApproveReceiveCommercial;

	/**
	* @var string $City
	*/
	public $City;

	/**
	* @var guid $CountryId
	*/
	public $CountryId;

	/**
	* @var string $Email
	*/
	public $Email;

	/**
	* @var string $FirstName
	*/
	public $FirstName;

	/**
	* @var string $LastName
	*/
	public $LastName;

	/**
	* @var string $MobileNumber
	*/
	public $MobileNumber;

	/**
	* @var string $Phone1AreaCode
	*/
	public $Phone1AreaCode;

	/**
	* @var string $Phone1CountryCode
	*/
	public $Phone1CountryCode;

	/**
	* @var string $Phone1Number
	*/
	public $Phone1Number;

	/**
	* @var string $PhoneAreaCode
	*/
	public $PhoneAreaCode;

	/**
	* @var string $PhoneCountryCode
	*/
	public $PhoneCountryCode;

	/**
	* @var string $PhoneNumber
	*/
	public $PhoneNumber;

	/**
	* @var string $PlaceOfBirth
	*/
	public $PlaceOfBirth;

	/**
	* @var boolean $SendSMS
	*/
	public $SendSMS;

	/**
	* @var string $State
	*/
	public $State;

	/**
	* @var string $ZipCode
	*/
	public $ZipCode;

}

/**
* Generated data proxy class for struct UpdateAccountDetailsResponse
*
*/
class UpdateAccountDetailsResponse {

	/**
	* @var AccountInfo $AccountInfo
	*/
	public $AccountInfo;

	/**
	* @var ResultInfo $Result
	*/
	public $Result;

}

/**
* Generated data proxy class for struct RealAccountRegistrationRequest
*
*/
class RealAccountRegistrationRequest {

	/**
	* @var boolean $AcceptTermsAndConditions
	*/
	public $AcceptTermsAndConditions;

	/**
	* @var PickListInfo $AccountType
	*/
	public $AccountType;

	/**
	* @var string $Address1
	*/
	public $Address1;

	/**
	* @var string $Address2
	*/
	public $Address2;

	/**
	* @var boolean $ApiTrading
	*/
	public $ApiTrading;

	/**
	* @var PickListInfo $AverageTradeSize
	*/
	public $AverageTradeSize;

	/**
	* @var PickListInfo $CfdTradingExperience
	*/
	public $CfdTradingExperience;

	/**
	* @var string $City
	*/
	public $City;

	/**
	* @var guid $CountryOfCitizenshipId
	*/
	public $CountryOfCitizenshipId;

	/**
	* @var PickListInfo $CurrenciesTradingExperience
	*/
	public $CurrenciesTradingExperience;

	/**
	* @var dateTime $DateOfBirth
	*/
	public $DateOfBirth;

	/**
	* @var int $EstimatedAnnualIncome
	*/
	public $EstimatedAnnualIncome;

	/**
	* @var int $EstimatedNetWorth
	*/
	public $EstimatedNetWorth;

	/**
	* @var string $ExistingTPAccount
	*/
	public $ExistingTPAccount;

	/**
	* @var PickListInfo $FuturesTradingExperience
	*/
	public $FuturesTradingExperience;

	/**
	* @var string $GroupName
	*/
	public $GroupName;

	/**
	* @var boolean $HasDemoExperience
	*/
	public $HasDemoExperience;

	/**
	* @var PickListInfo $HowDidYouHearAboutUs
	*/
	public $HowDidYouHearAboutUs;

	/**
	* @var guid $LoggedInAccountId
	*/
	public $LoggedInAccountId;

	/**
	* @var boolean $ManagedAccount
	*/
	public $ManagedAccount;

	/**
	* @var string $MobileNumber
	*/
	public $MobileNumber;

	/**
	* @var PickListInfo $NumberOfTimesTradedInPastYear
	*/
	public $NumberOfTimesTradedInPastYear;

	/**
	* @var string $Occupation
	*/
	public $Occupation;

	/**
	* @var PickListInfo $OptionsTradingExperience
	*/
	public $OptionsTradingExperience;

	/**
	* @var string $Password
	*/
	public $Password;

	/**
	* @var string $PlaceOfBirth
	*/
	public $PlaceOfBirth;

	/**
	* @var PickListInfo $SecuritiesTradingExperience
	*/
	public $SecuritiesTradingExperience;

	/**
	* @var boolean $SendSMS
	*/
	public $SendSMS;

	/**
	* @var string $SocialSecurityNumber
	*/
	public $SocialSecurityNumber;

	/**
	* @var string $State
	*/
	public $State;

	/**
	* @var guid $TradingPlatformId
	*/
	public $TradingPlatformId;

	/**
	* @var string $ZipCode
	*/
	public $ZipCode;

}

/**
* Generated data proxy class for struct AccountRegistrationRequest
*
*/
class AccountRegistrationRequest {

	/**
	* @var ArrayOfDynamicAttributeInfo $AdditionalAttributes
	*/
	public $AdditionalAttributes;

	/**
	* @var string $AdditionalInfo1
	*/
	public $AdditionalInfo1;

	/**
	* @var string $AdditionalInfo2
	*/
	public $AdditionalInfo2;

	/**
	* @var string $AdditionalInfo3
	*/
	public $AdditionalInfo3;

	/**
	* @var boolean $ApproveReceiveCommercial
	*/
	public $ApproveReceiveCommercial;

	/**
	* @var guid $CountryId
	*/
	public $CountryId;

	/**
	* @var string $Email
	*/
	public $Email;

	/**
	* @var EnvironmentInfo $EnvironmentInfo
	*/
	public $EnvironmentInfo;

	/**
	* @var string $FirstName
	*/
	public $FirstName;

	/**
	* @var string $LastName
	*/
	public $LastName;

	/**
	* @var MarketingInfo $MarketingInfo
	*/
	public $MarketingInfo;

	/**
	* @var string $Phone1AreaCode
	*/
	public $Phone1AreaCode;

	/**
	* @var string $Phone1CountryCode
	*/
	public $Phone1CountryCode;

	/**
	* @var string $Phone1Number
	*/
	public $Phone1Number;

	/**
	* @var string $PhoneAreaCode
	*/
	public $PhoneAreaCode;

	/**
	* @var string $PhoneCountryCode
	*/
	public $PhoneCountryCode;

	/**
	* @var string $PhoneNumber
	*/
	public $PhoneNumber;

	/**
	* @var PickListInfo $Title
	*/
	public $Title;

}

/**
* Generated data proxy class for struct AccountRegistrationResponse
*
*/
class AccountRegistrationResponse {

	/**
	* @var guid $AccountId
	*/
	public $AccountId;

	/**
	* @var CurrencyInfo $BaseCurrency
	*/
	public $BaseCurrency;

	/**
	* @var dateTime $ExpirationTime
	*/
	public $ExpirationTime;

	/**
	* @var ResultInfo $Result
	*/
	public $Result;

	/**
	* @var string $TradingPlatform
	*/
	public $TradingPlatform;

	/**
	* @var guid $TradingPlatformAccountId
	*/
	public $TradingPlatformAccountId;

	/**
	* @var string $TradingPlatformAccountName
	*/
	public $TradingPlatformAccountName;

	/**
	* @var string $TradingPlatformAccountPassword
	*/
	public $TradingPlatformAccountPassword;

	/**
	* @var TradingPlatformAccountType $TradingPlatformAccountType
	*/
	public $TradingPlatformAccountType;

}

/**
* Generated data proxy class for string TradingPlatformAccountType
*
*/
class TradingPlatformAccountType {

}

/**
* Generated data proxy class for struct DuplicationHandlingResult
*
*/
class DuplicationHandlingResult {

}

/**
* Generated data proxy class for struct LeadAccountRegistrationRequest
*
*/
class LeadAccountRegistrationRequest {

	/**
	* @var guid $CountryOfCitizenshipId
	*/
	public $CountryOfCitizenshipId;

}

/**
* Generated data proxy class for struct DemoAccountRegistrationRequest
*
*/
class DemoAccountRegistrationRequest {

	/**
	* @var string $GroupName
	*/
	public $GroupName;

	/**
	* @var guid $LoggedInAccountId
	*/
	public $LoggedInAccountId;

	/**
	* @var string $Password
	*/
	public $Password;

	/**
	* @var string $PlaceOfBirth
	*/
	public $PlaceOfBirth;

	/**
	* @var guid $TradingPlatformId
	*/
	public $TradingPlatformId;

}

/**
* Generated data proxy class for struct CaseCreationRequest
*
*/
class CaseCreationRequest {

	/**
	* @var guid $AccountId
	*/
	public $AccountId;

	/**
	* @var double $Amount
	*/
	public $Amount;

	/**
	* @var string $CardHolderIdentityNumber
	*/
	public $CardHolderIdentityNumber;

	/**
	* @var string $CardHolderName
	*/
	public $CardHolderName;

	/**
	* @var string $CardLast4Digits
	*/
	public $CardLast4Digits;

	/**
	* @var PickListInfo $CardType
	*/
	public $CardType;

	/**
	* @var string $ClearingResponse
	*/
	public $ClearingResponse;

	/**
	* @var PickListInfo $ContactMethod
	*/
	public $ContactMethod;

	/**
	* @var guid $CountryId
	*/
	public $CountryId;

	/**
	* @var guid $CurrencyId
	*/
	public $CurrencyId;

	/**
	* @var string $Description
	*/
	public $Description;

	/**
	* @var string $Email
	*/
	public $Email;

	/**
	* @var EnvironmentInfo $EnvironmentInfo
	*/
	public $EnvironmentInfo;

	/**
	* @var string $FirstName
	*/
	public $FirstName;

	/**
	* @var string $LastName
	*/
	public $LastName;

	/**
	* @var string $PhoneAreaCode
	*/
	public $PhoneAreaCode;

	/**
	* @var string $PhoneCountryCode
	*/
	public $PhoneCountryCode;

	/**
	* @var string $PhoneNumber
	*/
	public $PhoneNumber;

	/**
	* @var DayOfWeek $PreferredContactDay
	*/
	public $PreferredContactDay;

	/**
	* @var PickListInfo $PreferredContactHours
	*/
	public $PreferredContactHours;

	/**
	* @var string $Title
	*/
	public $Title;

}

/**
* Generated data proxy class for struct WithdrawalRequest
*
*/
class WithdrawalRequest {

	/**
	* @var guid $AccountId
	*/
	public $AccountId;

	/**
	* @var double $Amount
	*/
	public $Amount;

	/**
	* @var string $CaseTitle
	*/
	public $CaseTitle;

	/**
	* @var CreditCardInfo $CreditCardWithdrawalDetails
	*/
	public $CreditCardWithdrawalDetails;

	/**
	* @var guid $CurrencyId
	*/
	public $CurrencyId;

	/**
	* @var string $Description
	*/
	public $Description;

	/**
	* @var string $TradingPlatformAccountName
	*/
	public $TradingPlatformAccountName;

	/**
	* @var WebMoneyInfo $WebMoneyWithdrawalDetails
	*/
	public $WebMoneyWithdrawalDetails;

	/**
	* @var WireTransferInfo $WireTransferWithdrawalDetails
	*/
	public $WireTransferWithdrawalDetails;

	/**
	* @var MoneyTransactionMethod $WithdrawalMethod
	*/
	public $WithdrawalMethod;

}

/**
* Generated data proxy class for struct CreditCardInfo
*
*/
class CreditCardInfo {

	/**
	* @var string $CardExpirationMonth
	*/
	public $CardExpirationMonth;

	/**
	* @var string $CardExpirationYear
	*/
	public $CardExpirationYear;

	/**
	* @var string $CardIssuingBank
	*/
	public $CardIssuingBank;

	/**
	* @var string $HolderIdentity
	*/
	public $HolderIdentity;

	/**
	* @var string $HolderName
	*/
	public $HolderName;

	/**
	* @var string $Number
	*/
	public $Number;

	/**
	* @var PickListInfo $Type
	*/
	public $Type;

}

/**
* Generated data proxy class for struct WebMoneyInfo
*
*/
class WebMoneyInfo {

	/**
	* @var string $Email
	*/
	public $Email;

	/**
	* @var string $Number
	*/
	public $Number;

}

/**
* Generated data proxy class for struct WireTransferInfo
*
*/
class WireTransferInfo {

	/**
	* @var string $BankAccountNumber
	*/
	public $BankAccountNumber;

	/**
	* @var string $BankAddress
	*/
	public $BankAddress;

	/**
	* @var string $BankName
	*/
	public $BankName;

	/**
	* @var string $Beneficiary
	*/
	public $Beneficiary;

	/**
	* @var string $SwiftCode
	*/
	public $SwiftCode;

}

/**
* Generated data proxy class for string MoneyTransactionMethod
*
*/
class MoneyTransactionMethod {

}

/**
* Generated data proxy class for struct CreditCardDepositResponse
*
*/
class CreditCardDepositResponse {

	/**
	* @var ResultInfo $Result
	*/
	public $Result;

	/**
	* @var boolean $TradingPlatformUpdated
	*/
	public $TradingPlatformUpdated;

}

/**
* Generated data proxy class for struct MonetaryTransactionRequest
*
*/
class MonetaryTransactionRequest {

	/**
	* @var ArrayOfDynamicAttributeInfo $AdditionalAttributes
	*/
	public $AdditionalAttributes;

	/**
	* @var boolean $IsCancellationTransaction
	*/
	public $IsCancellationTransaction;

	/**
	* @var MonetaryTransactionRequestInfo $MonetaryTransactionRequestInfo
	*/
	public $MonetaryTransactionRequestInfo;

	/**
	* @var boolean $ShouldAutoApprove
	*/
	public $ShouldAutoApprove;

	/**
	* @var boolean $UpdateTPOnApprove
	*/
	public $UpdateTPOnApprove;

}

/**
* Generated data proxy class for struct MonetaryTransactionRequestInfo
*
*/
class MonetaryTransactionRequestInfo {

	/**
	* @var string $AffiliateTransactionId
	*/
	public $AffiliateTransactionId;

	/**
	* @var double $Amount
	*/
	public $Amount;

	/**
	* @var string $InternalComment
	*/
	public $InternalComment;

	/**
	* @var double $OriginalAmount
	*/
	public $OriginalAmount;

	/**
	* @var PickListInfo $OriginalCurrency
	*/
	public $OriginalCurrency;

	/**
	* @var PaymentInfo $PaymentInfo
	*/
	public $PaymentInfo;

	/**
	* @var guid $TradingPlatformAccountId
	*/
	public $TradingPlatformAccountId;

	/**
	* @var string $TransactionReference
	*/
	public $TransactionReference;

}

/**
* Generated data proxy class for struct PaymentInfo
*
*/
class PaymentInfo {

}

/**
* Generated data proxy class for struct KashUPaymentInfo
*
*/
class KashUPaymentInfo {

}

/**
* Generated data proxy class for struct CashPaymentInfo
*
*/
class CashPaymentInfo {

}

/**
* Generated data proxy class for struct ChequePaymentInfo
*
*/
class ChequePaymentInfo {

}

/**
* Generated data proxy class for struct CreditCardPaymentInfo
*
*/
class CreditCardPaymentInfo {

	/**
	* @var PickListInfo $CardAcquirer
	*/
	public $CardAcquirer;

	/**
	* @var string $CardAcquirerReference
	*/
	public $CardAcquirerReference;

	/**
	* @var string $CardExpirationMonth
	*/
	public $CardExpirationMonth;

	/**
	* @var string $CardExpirationYear
	*/
	public $CardExpirationYear;

	/**
	* @var string $CardHolderIdentityNumber
	*/
	public $CardHolderIdentityNumber;

	/**
	* @var string $CardHolderName
	*/
	public $CardHolderName;

	/**
	* @var string $CardIssuingBank
	*/
	public $CardIssuingBank;

	/**
	* @var string $CardLast4Digits
	*/
	public $CardLast4Digits;

	/**
	* @var PickListInfo $CardType
	*/
	public $CardType;

	/**
	* @var string $ClearingResponse
	*/
	public $ClearingResponse;

}

/**
* Generated data proxy class for struct MoneyBookersPaymentInfo
*
*/
class MoneyBookersPaymentInfo {

}

/**
* Generated data proxy class for struct EWalletPaymentInfo
*
*/
class EWalletPaymentInfo {

	/**
	* @var string $Email
	*/
	public $Email;

	/**
	* @var string $Number
	*/
	public $Number;

}

/**
* Generated data proxy class for struct WebMoneyRequestInfo
*
*/
class WebMoneyRequestInfo {

}

/**
* Generated data proxy class for struct NetellerPaymentInfo
*
*/
class NetellerPaymentInfo {

}

/**
* Generated data proxy class for struct PaypalPaymentInfo
*
*/
class PaypalPaymentInfo {

}

/**
* Generated data proxy class for struct WesternUnionPaymentInfo
*
*/
class WesternUnionPaymentInfo {

}

/**
* Generated data proxy class for struct WireTransferPaymentInfo
*
*/
class WireTransferPaymentInfo {

	/**
	* @var string $BankAccountNumber
	*/
	public $BankAccountNumber;

	/**
	* @var string $BankAddress
	*/
	public $BankAddress;

	/**
	* @var string $BankName
	*/
	public $BankName;

	/**
	* @var string $Benificiary
	*/
	public $Benificiary;

	/**
	* @var string $BrokerBankAccountDetails
	*/
	public $BrokerBankAccountDetails;

	/**
	* @var string $SwiftCode
	*/
	public $SwiftCode;

}

/**
* Generated data proxy class for struct InternalPaymentInfo
*
*/
class InternalPaymentInfo {

}

/**
* Generated data proxy class for struct WithdrawalMonetaryTransactionRequest
*
*/
class WithdrawalMonetaryTransactionRequest {

	/**
	* @var boolean $WithdrawalCompleteTradingRequest
	*/
	public $WithdrawalCompleteTradingRequest;

	/**
	* @var boolean $WithdrawalHasDocuments
	*/
	public $WithdrawalHasDocuments;

	/**
	* @var boolean $WithdrawalHasEnoughFundsInTradingPlatform
	*/
	public $WithdrawalHasEnoughFundsInTradingPlatform;

	/**
	* @var boolean $WithdrawalIsMethodOfPaymentSuitable
	*/
	public $WithdrawalIsMethodOfPaymentSuitable;

	/**
	* @var boolean $WithdrawalManagementApproval
	*/
	public $WithdrawalManagementApproval;

	/**
	* @var boolean $WithdrawalPaid
	*/
	public $WithdrawalPaid;

	/**
	* @var string $WithdrawalPaymentDetails
	*/
	public $WithdrawalPaymentDetails;

	/**
	* @var PickListInfo $WithdrawalReason
	*/
	public $WithdrawalReason;

	/**
	* @var dateTime $WithdrawalRequestDate
	*/
	public $WithdrawalRequestDate;

	/**
	* @var boolean $WithdrawalRetentionOwnerApproval
	*/
	public $WithdrawalRetentionOwnerApproval;

	/**
	* @var PickListInfo $WithdrawalStatus
	*/
	public $WithdrawalStatus;

}

/**
* Generated data proxy class for struct DepositRequest
*
*/
class DepositRequest {

}

/**
* Generated data proxy class for struct BonusRequest
*
*/
class BonusRequest {

}

/**
* Generated data proxy class for struct TransferBetweenTPAccountsRequest
*
*/
class TransferBetweenTPAccountsRequest {

	/**
	* @var guid $OppositeAccountId
	*/
	public $OppositeAccountId;

}

/**
* Generated data proxy class for struct MonetaryTransactionResponse
*
*/
class MonetaryTransactionResponse {

	/**
	* @var ResultInfo $Result
	*/
	public $Result;

	/**
	* @var boolean $TradingPlatformUpdated
	*/
	public $TradingPlatformUpdated;

}

/**
* Generated data proxy class for struct TradingHistoryResponse
*
*/
class TradingHistoryResponse {

	/**
	* @var ArrayOfClosedPositionInfo $ClosedPositions
	*/
	public $ClosedPositions;

	/**
	* @var ResultInfo $Result
	*/
	public $Result;

}

/**
* Generated data proxy class for struct ArrayOfClosedPositionInfo
*
*/
class ArrayOfClosedPositionInfo {

	/**
	* @var ClosedPositionInfo $ClosedPositionInfo
	*/
	public $ClosedPositionInfo;

}

/**
* Generated data proxy class for struct ClosedPositionInfo
*
*/
class ClosedPositionInfo {

	/**
	* @var ActionType $ActionType
	*/
	public $ActionType;

	/**
	* @var double $Amount
	*/
	public $Amount;

	/**
	* @var double $CloseRate
	*/
	public $CloseRate;

	/**
	* @var dateTime $CloseTime
	*/
	public $CloseTime;

	/**
	* @var double $CommissionForAgentInAccountCurrency
	*/
	public $CommissionForAgentInAccountCurrency;

	/**
	* @var double $CommissionInAccountCurrency
	*/
	public $CommissionInAccountCurrency;

	/**
	* @var string $InstrumentName
	*/
	public $InstrumentName;

	/**
	* @var double $OpenRate
	*/
	public $OpenRate;

	/**
	* @var dateTime $OpenTime
	*/
	public $OpenTime;

	/**
	* @var string $OrderID
	*/
	public $OrderID;

	/**
	* @var double $ProfitInAccountCurrency
	*/
	public $ProfitInAccountCurrency;

	/**
	* @var double $RolloverInAccountCurrency
	*/
	public $RolloverInAccountCurrency;

	/**
	* @var int $Spread
	*/
	public $Spread;

	/**
	* @var double $StopLoss
	*/
	public $StopLoss;

	/**
	* @var double $TakeProfit
	*/
	public $TakeProfit;

	/**
	* @var string $TradingPlatfromAccountName
	*/
	public $TradingPlatfromAccountName;

}

/**
* Generated data proxy class for string ActionType
*
*/
class ActionType {

}

/**
* Generated data proxy class for struct AccountMonetaryStatementResponse
*
*/
class AccountMonetaryStatementResponse {

	/**
	* @var ArrayOfMonetaryTransaction $MonetaryTransactions
	*/
	public $MonetaryTransactions;

	/**
	* @var ResultInfo $Result
	*/
	public $Result;

}

/**
* Generated data proxy class for struct ArrayOfMonetaryTransaction
*
*/
class ArrayOfMonetaryTransaction {

	/**
	* @var MonetaryTransaction $MonetaryTransaction
	*/
	public $MonetaryTransaction;

}

/**
* Generated data proxy class for struct MonetaryTransaction
*
*/
class MonetaryTransaction {

	/**
	* @var string $AffiliateTransactionId
	*/
	public $AffiliateTransactionId;

	/**
	* @var double $Amount
	*/
	public $Amount;

	/**
	* @var boolean $Approved
	*/
	public $Approved;

	/**
	* @var CurrencyInfo $BaseCurrency
	*/
	public $BaseCurrency;

	/**
	* @var double $BaseCurrencyAmount
	*/
	public $BaseCurrencyAmount;

	/**
	* @var PickListInfo $CreaditCardType
	*/
	public $CreaditCardType;

	/**
	* @var dateTime $CreationTime
	*/
	public $CreationTime;

	/**
	* @var CreditCardInfo $CreditCardDetails
	*/
	public $CreditCardDetails;

	/**
	* @var CurrencyInfo $Currency
	*/
	public $Currency;

	/**
	* @var double $ExchangeRate
	*/
	public $ExchangeRate;

	/**
	* @var MonetaryTransactionInternalType $InternalType
	*/
	public $InternalType;

	/**
	* @var double $OriginalAmount
	*/
	public $OriginalAmount;

	/**
	* @var PickListInfo $OriginalCurrency
	*/
	public $OriginalCurrency;

	/**
	* @var MoneyTransactionMethod $PaymentMethod
	*/
	public $PaymentMethod;

	/**
	* @var string $TradingPlatformAccountName
	*/
	public $TradingPlatformAccountName;

	/**
	* @var MonetaryTransactionType $Type
	*/
	public $Type;

	/**
	* @var double $UsdValue
	*/
	public $UsdValue;

	/**
	* @var WebMoneyInfo $WebMoneyDetails
	*/
	public $WebMoneyDetails;

	/**
	* @var WireTransferInfo $WireTransferDetails
	*/
	public $WireTransferDetails;

}

/**
* Generated data proxy class for string MonetaryTransactionInternalType
*
*/
class MonetaryTransactionInternalType {

}

/**
* Generated data proxy class for string MonetaryTransactionType
*
*/
class MonetaryTransactionType {

}

/**
* Generated data proxy class for struct ArrayOfPickListInfo
*
*/
class ArrayOfPickListInfo {

	/**
	* @var PickListInfo $PickListInfo
	*/
	public $PickListInfo;

}

/**
* Generated data proxy class for struct ArrayOfCountryInfo
*
*/
class ArrayOfCountryInfo {

	/**
	* @var CountryInfo $CountryInfo
	*/
	public $CountryInfo;

}

/**
* Generated data proxy class for struct CountryInfo
*
*/
class CountryInfo {

	/**
	* @var guid $Id
	*/
	public $Id;

	/**
	* @var string $Name
	*/
	public $Name;

	/**
	* @var string $ShortName
	*/
	public $ShortName;

}

/**
* Generated data proxy class for struct ArrayOfCurrencyInfo
*
*/
class ArrayOfCurrencyInfo {

	/**
	* @var CurrencyInfo $CurrencyInfo
	*/
	public $CurrencyInfo;

}

/**
* Generated data proxy class for struct CreditCardDepositRequest
*
*/
class CreditCardDepositRequest {

	/**
	* @var double $Amount
	*/
	public $Amount;

	/**
	* @var PickListInfo $CardAcquirer
	*/
	public $CardAcquirer;

	/**
	* @var string $CardAcquirerReference
	*/
	public $CardAcquirerReference;

	/**
	* @var string $CardExpirationMonth
	*/
	public $CardExpirationMonth;

	/**
	* @var string $CardExpirationYear
	*/
	public $CardExpirationYear;

	/**
	* @var string $CardHolderIdentityNumber
	*/
	public $CardHolderIdentityNumber;

	/**
	* @var string $CardHolderName
	*/
	public $CardHolderName;

	/**
	* @var string $CardIssuingBank
	*/
	public $CardIssuingBank;

	/**
	* @var string $CardLast4Digits
	*/
	public $CardLast4Digits;

	/**
	* @var PickListInfo $CardType
	*/
	public $CardType;

	/**
	* @var string $ClearingResponse
	*/
	public $ClearingResponse;

	/**
	* @var string $DefaultCaseTitle
	*/
	public $DefaultCaseTitle;

	/**
	* @var double $OriginalAmount
	*/
	public $OriginalAmount;

	/**
	* @var PickListInfo $OriginalCurrency
	*/
	public $OriginalCurrency;

	/**
	* @var guid $TradingPlatformAccountId
	*/
	public $TradingPlatformAccountId;

}

/**
* Generated data proxy class for struct LoginAccount
*
*/
class LoginAccount {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var string $tradingPlatformAccountName
	*/
	public $tradingPlatformAccountName;

	/**
	* @var string $tradingPlatformAccountPassword
	*/
	public $tradingPlatformAccountPassword;

}

/**
* Generated data proxy class for struct LoginAccountResponse
*
*/
class LoginAccountResponse {

	/**
	* @var LoginResponse $LoginAccountResult
	*/
	public $LoginAccountResult;

}

/**
* Generated data proxy class for struct ChangePassword
*
*/
class ChangePassword {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var string $tradingPlatformAccountName
	*/
	public $tradingPlatformAccountName;

	/**
	* @var string $tradingPlatformAccountOldPassword
	*/
	public $tradingPlatformAccountOldPassword;

	/**
	* @var string $tradingPlatformAccountNewPassword
	*/
	public $tradingPlatformAccountNewPassword;

}

/**
* Generated data proxy class for struct ChangePasswordResponse
*
*/
class ChangePasswordResponse {

	/**
	* @var ResultInfo $ChangePasswordResult
	*/
	public $ChangePasswordResult;

}

/**
* Generated data proxy class for struct GetAccountDetails
*
*/
class GetAccountDetails {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var AccountDetailsRequest $accountDetailsRequest
	*/
	public $accountDetailsRequest;

}

/**
* Generated data proxy class for struct GetAccountDetailsResponse
*
*/
class GetAccountDetailsResponse {

	/**
	* @var AccountInfoResponse $GetAccountDetailsResult
	*/
	public $GetAccountDetailsResult;

}

/**
* Generated data proxy class for struct GetTradingPlatformAccountDetails
*
*/
class GetTradingPlatformAccountDetails {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var guid $tradingPlatformAccountId
	*/
	public $tradingPlatformAccountId;

}

/**
* Generated data proxy class for struct GetTradingPlatformAccountDetailsResponse
*
*/
class GetTradingPlatformAccountDetailsResponse {

	/**
	* @var TradingPlatformAccountInfoResponse $GetTradingPlatformAccountDetailsResult
	*/
	public $GetTradingPlatformAccountDetailsResult;

}

/**
* Generated data proxy class for struct GetTradingPlatformAccountBalance
*
*/
class GetTradingPlatformAccountBalance {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var string $tradingPlatformAccountName
	*/
	public $tradingPlatformAccountName;

}

/**
* Generated data proxy class for struct GetTradingPlatformAccountBalanceResponse
*
*/
class GetTradingPlatformAccountBalanceResponse {

	/**
	* @var TradingPlatformAccountBalanceResponse $GetTradingPlatformAccountBalanceResult
	*/
	public $GetTradingPlatformAccountBalanceResult;

}

/**
* Generated data proxy class for struct UpdateAccountDetails
*
*/
class UpdateAccountDetails {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var UpdateAccountDetailsRequest $updateAccountDetailsRequest
	*/
	public $updateAccountDetailsRequest;

}

/**
* Generated data proxy class for struct RegisterRealAccount
*
*/
class RegisterRealAccount {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var RealAccountRegistrationRequest $realAccountRegistrationRequest
	*/
	public $realAccountRegistrationRequest;

}

/**
* Generated data proxy class for struct RegisterRealAccountResponse
*
*/
class RegisterRealAccountResponse {

	/**
	* @var AccountRegistrationResponse $RegisterRealAccountResult
	*/
	public $RegisterRealAccountResult;

}

/**
* Generated data proxy class for struct RegisterLeadAccount
*
*/
class RegisterLeadAccount {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var LeadAccountRegistrationRequest $leadAccountRegistrationRequest
	*/
	public $leadAccountRegistrationRequest;

}

/**
* Generated data proxy class for struct RegisterLeadAccountResponse
*
*/
class RegisterLeadAccountResponse {

	/**
	* @var AccountRegistrationResponse $RegisterLeadAccountResult
	*/
	public $RegisterLeadAccountResult;

}

/**
* Generated data proxy class for struct RegisterDemoAccount
*
*/
class RegisterDemoAccount {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var DemoAccountRegistrationRequest $demoAccountRegistrationRequest
	*/
	public $demoAccountRegistrationRequest;

}

/**
* Generated data proxy class for struct RegisterDemoAccountResponse
*
*/
class RegisterDemoAccountResponse {

	/**
	* @var AccountRegistrationResponse $RegisterDemoAccountResult
	*/
	public $RegisterDemoAccountResult;

}

/**
* Generated data proxy class for struct CreateCase
*
*/
class CreateCase {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var CaseCreationRequest $caseCreationRequest
	*/
	public $caseCreationRequest;

}

/**
* Generated data proxy class for struct CreateCaseResponse
*
*/
class CreateCaseResponse {

	/**
	* @var ResultInfo $CreateCaseResult
	*/
	public $CreateCaseResult;

}

/**
* Generated data proxy class for struct CreateWithdrawalRequest
*
*/
class CreateWithdrawalRequest {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var WithdrawalRequest $withdrawalRequest
	*/
	public $withdrawalRequest;

}

/**
* Generated data proxy class for struct CreateWithdrawalRequestResponse
*
*/
class CreateWithdrawalRequestResponse {

	/**
	* @var ResultInfo $CreateWithdrawalRequestResult
	*/
	public $CreateWithdrawalRequestResult;

}

/**
* Generated data proxy class for struct CreateCreditCardDepositRequest
*
*/
class CreateCreditCardDepositRequest {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var CreditCardDepositRequest $creditCardDepositRequest
	*/
	public $creditCardDepositRequest;

}

/**
* Generated data proxy class for struct CreateCreditCardDepositRequestResponse
*
*/
class CreateCreditCardDepositRequestResponse {

	/**
	* @var CreditCardDepositResponse $CreateCreditCardDepositRequestResult
	*/
	public $CreateCreditCardDepositRequestResult;

}

/**
* Generated data proxy class for struct CreateMonetaryTransaction
*
*/
class CreateMonetaryTransaction {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var MonetaryTransactionRequest $monetaryTransactionRequest
	*/
	public $monetaryTransactionRequest;

}

/**
* Generated data proxy class for struct CreateMonetaryTransactionResponse
*
*/
class CreateMonetaryTransactionResponse {

	/**
	* @var MonetaryTransactionResponse $CreateMonetaryTransactionResult
	*/
	public $CreateMonetaryTransactionResult;

}

/**
* Generated data proxy class for struct GetTradingHistory
*
*/
class GetTradingHistory {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var guid $tradingPlatformAccountId
	*/
	public $tradingPlatformAccountId;

	/**
	* @var dateTime $startTime
	*/
	public $startTime;

	/**
	* @var dateTime $endTime
	*/
	public $endTime;

	/**
	* @var int $maxRows
	*/
	public $maxRows;

}

/**
* Generated data proxy class for struct GetTradingHistoryResponse
*
*/
class GetTradingHistoryResponse {

	/**
	* @var TradingHistoryResponse $GetTradingHistoryResult
	*/
	public $GetTradingHistoryResult;

}

/**
* Generated data proxy class for struct GetAccountMonetaryStatement
*
*/
class GetAccountMonetaryStatement {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var guid $accountId
	*/
	public $accountId;

}

/**
* Generated data proxy class for struct GetAccountMonetaryStatementResponse
*
*/
class GetAccountMonetaryStatementResponse {

	/**
	* @var AccountMonetaryStatementResponse $GetAccountMonetaryStatementResult
	*/
	public $GetAccountMonetaryStatementResult;

}

/**
* Generated data proxy class for struct ForgotYourPassword
*
*/
class ForgotYourPassword {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var string $tradingPlatformAccountName
	*/
	public $tradingPlatformAccountName;

	/**
	* @var string $email
	*/
	public $email;

}

/**
* Generated data proxy class for struct ForgotYourPasswordResponse
*
*/
class ForgotYourPasswordResponse {

	/**
	* @var ResultInfo $ForgotYourPasswordResult
	*/
	public $ForgotYourPasswordResult;

}

/**
* Generated data proxy class for struct UploadFile
*
*/
class UploadFile {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var guid $accountId
	*/
	public $accountId;

	/**
	* @var string $fileName
	*/
	public $fileName;

	/**
	* @var base64Binary $fileContent
	*/
	public $fileContent;

}

/**
* Generated data proxy class for struct UploadFileResponse
*
*/
class UploadFileResponse {

	/**
	* @var ResultInfo $UploadFileResult
	*/
	public $UploadFileResult;

}

/**
* Generated data proxy class for struct GetPickListInfoItems
*
*/
class GetPickListInfoItems {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var string $entityName
	*/
	public $entityName;

	/**
	* @var string $pickListAttributeName
	*/
	public $pickListAttributeName;

}

/**
* Generated data proxy class for struct GetPickListInfoItemsResponse
*
*/
class GetPickListInfoItemsResponse {

	/**
	* @var ArrayOfPickListInfo $GetPickListInfoItemsResult
	*/
	public $GetPickListInfoItemsResult;

}

/**
* Generated data proxy class for struct GetCountries
*
*/
class GetCountries {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

}

/**
* Generated data proxy class for struct GetCountriesResponse
*
*/
class GetCountriesResponse {

	/**
	* @var ArrayOfCountryInfo $GetCountriesResult
	*/
	public $GetCountriesResult;

}

/**
* Generated data proxy class for struct GetCurrencies
*
*/
class GetCurrencies {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

}

/**
* Generated data proxy class for struct GetCurrenciesResponse
*
*/
class GetCurrenciesResponse {

	/**
	* @var ArrayOfCurrencyInfo $GetCurrenciesResult
	*/
	public $GetCurrenciesResult;

}

/**
* Generated data proxy class for struct GetTradingPlatformGroups
*
*/
class GetTradingPlatformGroups {

	/**
	* @var guid $ownerUserId
	*/
	public $ownerUserId;

	/**
	* @var string $organizationName
	*/
	public $organizationName;

	/**
	* @var string $businessUnitName
	*/
	public $businessUnitName;

	/**
	* @var guid $tradingPlatformId
	*/
	public $tradingPlatformId;

}

/**
* Generated data proxy class for struct GetTradingPlatformGroupsResponse
*
*/
class GetTradingPlatformGroupsResponse {

	/**
	* @var ArrayOfstring $GetTradingPlatformGroupsResult
	*/
	public $GetTradingPlatformGroupsResult;

}

/**
* Generated data proxy class for struct ExceptionDetail
*
*/
class ExceptionDetail {

	/**
	* @var string $HelpLink
	*/
	public $HelpLink;

	/**
	* @var ExceptionDetail $InnerException
	*/
	public $InnerException;

	/**
	* @var string $Message
	*/
	public $Message;

	/**
	* @var string $StackTrace
	*/
	public $StackTrace;

	/**
	* @var string $Type
	*/
	public $Type;

}

